import React, { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { BarChart3, Boxes, ClipboardList, Copy, Edit3, LogOut, Megaphone, PackagePlus, Settings2, Tag, Trash2, Truck, Users } from 'lucide-react';
import { useStore } from '../../context/StoreContext';
import { useToast } from '../../context/ToastContext';
import { AdminLoginModal } from './AdminLoginModal';
import { ProductModal } from './ProductModal';
import { CategoryConfig, Product, StoreSettings } from '../../types';

type Tab = 'overview' | 'products' | 'orders' | 'promos' | 'categories' | 'site';
const tabs: { id: Tab; label: string; icon: React.ElementType }[] = [
  { id: 'overview', label: 'Overview', icon: BarChart3 }, { id: 'products', label: 'Products', icon: Boxes },
  { id: 'orders', label: 'Orders', icon: ClipboardList }, { id: 'promos', label: 'Promotions', icon: Tag },
  { id: 'categories', label: 'Categories', icon: Users }, { id: 'site', label: 'Website settings', icon: Settings2 },
];

const Field: React.FC<{ label: string; value: string | number; onChange: (v: string) => void; type?: string }> = ({ label, value, onChange, type = 'text' }) => <label className="block text-xs font-semibold text-stone-600">{label}<input type={type} value={value} onChange={e => onChange(e.target.value)} className="mt-1.5 w-full rounded-xl border border-stone-200 bg-white px-3 py-2.5 text-sm text-stone-900 outline-none focus:border-[#8A3D52]" /></label>;

export const AdminPortal: React.FC = () => {
  const store = useStore(); const { showToast } = useToast(); const navigate = useNavigate();
  const [loginOpen, setLoginOpen] = useState(true); const [tab, setTab] = useState<Tab>('overview');
  const [editing, setEditing] = useState<Product | null>(null); const [productModalOpen, setProductModalOpen] = useState(false);
  const [promo, setPromo] = useState({ code: '', discountValue: '10', minSpend: '0', description: '', discountType: 'percentage' as 'percentage' | 'fixed', freeShipping: false });
  const [category, setCategory] = useState({ name: '', slug: '', description: '', department: 'beauty' as 'beauty' | 'groceries', image: '' });
  const revenue = useMemo(() => store.orders.filter(o => o.paymentStatus === 'paid').reduce((sum, o) => sum + o.total, 0), [store.orders]);
  if (!store.adminSession.isLoggedIn) return <AdminLoginModal isOpen={loginOpen} onClose={() => { setLoginOpen(false); navigate('/'); }} onSuccess={() => setLoginOpen(false)} />;
  const saveSettings = (key: keyof StoreSettings, value: string | boolean) => store.updateStoreSettings({ [key]: typeof value === 'string' && ['freeDeliveryThreshold', 'standardShippingFee', 'expressShippingFee', 'intercityShippingFee'].includes(key) ? Number(value) : value } as Partial<StoreSettings>);
  const addPromo = (e: React.FormEvent) => { e.preventDefault(); if (!promo.code || !promo.description) return showToast('Add a code and description first'); store.addPromoCode({ code: promo.code, discountType: promo.discountType, discountValue: Number(promo.discountValue), minSpend: Number(promo.minSpend) || undefined, freeShipping: promo.freeShipping, isActive: true, description: promo.description }); setPromo({ code: '', discountValue: '10', minSpend: '0', description: '', discountType: 'percentage', freeShipping: false }); showToast('Promotion is live'); };
  const addCategory = (e: React.FormEvent) => { e.preventDefault(); const id = category.slug.trim().toLowerCase().replace(/[^a-z0-9-]/g, '-') || `category-${Date.now()}`; if (!category.name || store.categories.some(c => c.id === id)) return showToast('Use a unique category name and slug'); store.addCategory({ ...category, id: id as CategoryConfig['id'], slug: id, isActive: true, image: category.image || 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?auto=format&fit=crop&w=600&q=80' }); setCategory({ name: '', slug: '', description: '', department: 'beauty', image: '' }); showToast('Category added'); };
  return <div className="min-h-screen bg-[#f7f4f1] text-stone-900"><div className="mx-auto flex max-w-7xl gap-6 p-4 sm:p-6">
    <aside className="hidden w-60 shrink-0 rounded-3xl bg-[#25191d] p-5 text-white md:block"><div className="mb-8"><div className="text-xs font-bold uppercase tracking-[.22em] text-[#e8b792]">CR Cosmetics</div><h1 className="mt-2 text-xl font-serif">Admin portal</h1><p className="mt-2 text-xs text-stone-400">Signed in as {store.adminSession.adminName}</p></div><nav className="space-y-1">{tabs.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm transition ${tab === id ? 'bg-[#8A3D52] text-white' : 'text-stone-300 hover:bg-white/10'}`}><Icon className="h-4 w-4" />{label}</button>)}</nav><button onClick={() => { store.logoutAdmin(); navigate('/'); }} className="mt-10 flex items-center gap-2 text-xs text-stone-400 hover:text-white"><LogOut className="h-4 w-4" />Sign out</button></aside>
    <section className="min-w-0 flex-1"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#8A3D52]">Store command center</p><h2 className="text-2xl font-serif font-bold">{tabs.find(t => t.id === tab)?.label}</h2></div><button onClick={() => navigate('/')} className="rounded-full border border-stone-200 bg-white px-4 py-2 text-xs font-bold">View website</button></div><div className="mb-5 flex gap-2 overflow-x-auto md:hidden">{tabs.map(t => <button key={t.id} onClick={() => setTab(t.id)} className={`whitespace-nowrap rounded-full px-3 py-2 text-xs ${tab === t.id ? 'bg-[#8A3D52] text-white' : 'bg-white'}`}>{t.label}</button>)}</div>
    {tab === 'overview' && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Catalog products', store.products.length, Boxes], ['Orders received', store.orders.length, ClipboardList], ['Paid sales', `GHS ${revenue.toFixed(2)}`, BarChart3], ['Low stock', store.products.filter(p => p.stockCount <= 5).length, Truck]].map(([label, value, Icon]: any) => <div key={label} className="rounded-2xl border border-stone-200 bg-white p-5"><Icon className="mb-5 h-5 w-5 text-[#8A3D52]" /><p className="text-xs text-stone-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>)}</div><div className="mt-6 rounded-2xl border border-stone-200 bg-white p-5"><h3 className="font-bold">Quick actions</h3><div className="mt-4 flex flex-wrap gap-3"><button onClick={() => { setEditing(null); setProductModalOpen(true); }} className="rounded-xl bg-[#8A3D52] px-4 py-2.5 text-xs font-bold text-white"><PackagePlus className="mr-1 inline h-4 w-4" />Add product</button><button onClick={() => setTab('site')} className="rounded-xl border px-4 py-2.5 text-xs font-bold"><Megaphone className="mr-1 inline h-4 w-4" />Edit storefront</button></div></div></>}
    {tab === 'products' && <div className="rounded-2xl border border-stone-200 bg-white"><div className="flex items-center justify-between p-5"><div><h3 className="font-bold">Catalog control</h3><p className="text-xs text-stone-500">Publish, take down, edit, or permanently remove any catalog item.</p></div><button onClick={() => { setEditing(null); setProductModalOpen(true); }} className="rounded-xl bg-[#8A3D52] px-4 py-2.5 text-xs font-bold text-white">Add product</button></div><div className="divide-y divide-stone-100">{store.products.map(p => <div key={p.id} className="flex items-center gap-3 p-4"><img src={p.image} className="h-12 w-12 rounded-lg object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{p.name}</p><p className="text-xs text-stone-500">GHS {p.price.toFixed(2)} · {p.stockCount} in stock · {p.isPublished === false ? 'Taken down' : 'Live'}</p></div><button onClick={() => store.toggleProductPublication(p.id)} className={`rounded-full px-3 py-1.5 text-xs font-bold ${p.isPublished === false ? 'bg-stone-100 text-stone-600' : 'bg-emerald-100 text-emerald-700'}`}>{p.isPublished === false ? 'Publish' : 'Take down'}</button><button onClick={() => { setEditing(p); setProductModalOpen(true); }} className="p-2 text-[#8A3D52]"><Edit3 className="h-4 w-4" /></button><button onClick={() => { if (confirm(`Permanently delete ${p.name}? This cannot be undone.`)) { store.deleteProduct(p.id); showToast('Product permanently deleted'); } }} className="p-2 text-rose-600"><Trash2 className="h-4 w-4" /></button></div>)}</div></div>}
    {tab === 'orders' && <div className="space-y-3">{store.orders.length === 0 ? <div className="rounded-2xl border border-dashed border-stone-300 p-10 text-center text-sm text-stone-500">Orders will appear here as customers check out.</div> : store.orders.map(o => <div key={o.id} className="rounded-2xl border border-stone-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><b>{o.orderNumber}</b><p className="mt-1 text-xs text-stone-500">{o.shippingAddress.fullName} · GHS {o.total.toFixed(2)} · {o.paymentStatus}</p></div><select value={o.status} onChange={e => store.updateOrderStatus(o.id, e.target.value as any)} className="rounded-lg border px-3 py-2 text-xs">{['Confirmed','Processing','Packing Order','Out for Delivery','Delivered'].map(s => <option key={s}>{s}</option>)}</select></div></div>)}</div>}
    {tab === 'promos' && <div className="grid gap-5 lg:grid-cols-[1fr,1.2fr]"><form onSubmit={addPromo} className="space-y-3 rounded-2xl border border-stone-200 bg-white p-5"><h3 className="font-bold">Create promotion</h3><Field label="Promo code" value={promo.code} onChange={v => setPromo({ ...promo, code: v.toUpperCase() })}/><Field label="Customer message" value={promo.description} onChange={v => setPromo({ ...promo, description: v })}/><div className="grid grid-cols-2 gap-3"><Field label="Discount" type="number" value={promo.discountValue} onChange={v => setPromo({ ...promo, discountValue: v })}/><Field label="Minimum spend" type="number" value={promo.minSpend} onChange={v => setPromo({ ...promo, minSpend: v })}/></div><button className="rounded-xl bg-[#8A3D52] px-4 py-2.5 text-xs font-bold text-white">Publish promotion</button></form><div className="space-y-3">{store.promoCodes.map(p => <div key={p.id} className="rounded-2xl border border-stone-200 bg-white p-4"><div className="flex justify-between"><div><b>{p.code}</b><p className="mt-1 text-xs text-stone-500">{p.description}</p></div><button onClick={() => store.togglePromoCode(p.code)} className={`rounded-full px-3 py-1 text-xs font-bold ${p.isActive ? 'bg-emerald-100 text-emerald-700' : 'bg-stone-100 text-stone-600'}`}>{p.isActive ? 'Active' : 'Inactive'}</button></div><div className="mt-3 flex gap-3 text-xs"><span>{p.discountValue}{p.discountType === 'percentage' ? '%' : ' GHS'} off</span><button onClick={() => store.deletePromoCode(p.id)} className="text-rose-600">Remove</button></div></div>)}</div></div>}
    {tab === 'categories' && <div className="grid gap-5 lg:grid-cols-[1fr,1.2fr]"><form onSubmit={addCategory} className="space-y-3 rounded-2xl border border-stone-200 bg-white p-5"><h3 className="font-bold">Add category</h3><Field label="Name" value={category.name} onChange={v => setCategory({ ...category, name: v })}/><Field label="URL slug" value={category.slug} onChange={v => setCategory({ ...category, slug: v })}/><Field label="Description" value={category.description} onChange={v => setCategory({ ...category, description: v })}/><Field label="Image URL" value={category.image} onChange={v => setCategory({ ...category, image: v })}/><select value={category.department} onChange={e => setCategory({ ...category, department: e.target.value as any })} className="w-full rounded-xl border px-3 py-2.5 text-sm"><option value="beauty">Beauty</option><option value="groceries">Groceries</option></select><button className="rounded-xl bg-[#8A3D52] px-4 py-2.5 text-xs font-bold text-white">Add category</button></form><div className="space-y-3">{store.categories.map(c => <div className="flex items-center gap-3 rounded-2xl border border-stone-200 bg-white p-4" key={c.id}><img src={c.image} className="h-12 w-12 rounded-lg object-cover"/><div className="flex-1"><b>{c.name}</b><p className="text-xs text-stone-500">/{c.slug} · {c.department}</p></div><button onClick={() => store.toggleCategory(c.id)} className={`rounded-full px-3 py-1.5 text-xs font-bold ${c.isActive ? 'bg-emerald-100 text-emerald-700' : 'bg-stone-100 text-stone-600'}`}>{c.isActive ? 'Visible' : 'Hidden'}</button><button onClick={() => store.deleteCategory(c.id)} className="p-2 text-rose-600"><Trash2 className="h-4 w-4"/></button></div>)}</div></div>}
    {tab === 'site' && <div className="rounded-2xl border border-stone-200 bg-white p-5"><h3 className="font-bold">Live website configuration</h3><p className="mt-1 text-xs text-stone-500">Changes save immediately and update public components that use store settings.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{(['storeName','storeTagline','heroHeadline','heroSubtitle','heroBadge','heroButtonText','announcementText','announcementBg','storePhone','storeEmail','storeAddress','storeHours','whatsappNumber'] as (keyof StoreSettings)[]).map(key => <Field key={key} label={key.replace(/([A-Z])/g, ' $1')} value={store.storeSettings[key] as string} onChange={v => saveSettings(key, v)}/>)}</div><div className="mt-5 grid gap-4 md:grid-cols-4">{(['freeDeliveryThreshold','standardShippingFee','expressShippingFee','intercityShippingFee'] as (keyof StoreSettings)[]).map(key => <Field key={key} type="number" label={key.replace(/([A-Z])/g, ' $1')} value={store.storeSettings[key] as number} onChange={v => saveSettings(key, v)}/>)}</div><label className="mt-5 flex items-center gap-3 rounded-xl bg-amber-50 p-4 text-sm font-bold"><input type="checkbox" checked={store.storeSettings.maintenanceMode} onChange={e => saveSettings('maintenanceMode', e.target.checked)}/> Maintenance mode</label></div>}
    </section></div><ProductModal isOpen={productModalOpen} onClose={() => setProductModalOpen(false)} productToEdit={editing} /></div>;
};
